services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: api
    volumes:
      - .:/app
    networks:
      - netapi
    ports:
      - "8000:8000"
    


networks:
  netapi:
